### ISSUE TITLE
Bro, bomber.py not working on linux

### ISSUE THREAD

**Issue by lakshits11** [U7P4L-IN/CALL-BOMBER#1]
Getting following error on executing python BOMBER.py
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home/lakshit/Desktop/CALL-BOMBER/BOMBER.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by U7P4L-IN** [comment]
This tools is temporary off.bcz api not working
