### ISSUE TITLE
got error on ubuntu

### ISSUE THREAD

**Issue by hypervortex** [U7P4L-IN/CALL-BOMBER#11]
ubuntu@12gb-vortex-vs-zev:~/CALL-BOMBER$ python3 BOMBER.py
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home/ubuntu/CALL-BOMBER/BOMBER.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by U7P4L-IN** [comment]
_Api is Block  so this tool api is expired_
