### ISSUE TITLE
For me also doesn't work

### ISSUE THREAD

**Issue by profesionalleet1337** [U7P4L-IN/CALL-BOMBER#2]
For me also doesn't work .. Will it be fixed ?

**Comment by U7P4L-IN** [comment]
This tool for only Bangladesh 🙂

**Comment by profesionalleet1337** [comment]
> This tool for only Bangladesh 🙂

Ahh, understand you. Is there something working for EUROPE countries, like bulgaria, most of the tools I tried based on TextBel, but they doesn't offer a free anymore, so nothing works these days ? Could u advise or guide me, is there any instrument/ tool/ web-based site, that still work, and could be send some sms from computer to a number ?

**Comment by U7P4L-IN** [comment]
We need api for this work
