### ISSUE TITLE
Encoding name

### ISSUE THREAD

**Issue by still994** [U7P4L-IN/CALL-BOMBER#21]
what is the encoding name,I can't open ![Screenshot_2024-10-11-14-14-07-67_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/e178b4a1-4dff-4172-a53a-cbeff89c6393)

**Comment by U7P4L-IN** [comment]
`python3 BOMBER.py` run this

**Comment by U7P4L-IN** [comment]
so kindly run setup cmd and then try again or this tools only for bd users
