### ISSUE TITLE
It's not working!

### ISSUE THREAD

**Issue by Sofiul2904** [U7P4L-IN/CALL-BOMBER#9]
It's not working'

**Comment by U7P4L-IN** [comment]
i'm sry ,bcz this tools only for bd users and also i addd only bd sim api for bombing .

**Comment by Sofiul2904** [comment]
> i'm sry ,bcz this tools only for bd users and also i addd only bd sim api for bombing .

But i am From Bangladesh,, how to i run this tool please help me🥺
